-- World Bank WDI country/economy reference list
-- Source: https://api.worldbank.org/v2/country?format=json&per_page=400
-- WDI catalog: https://datacatalog.worldbank.org/search/dataset/0037712/world-development-indicators
-- Retrieved 2026-09-29. Aggregates (regions/income groups) excluded.
-- Serial numbers follow the WDI API's World Bank code order.
BEGIN;
CREATE TABLE IF NOT EXISTS wdi_countries (
    serial_no SMALLINT PRIMARY KEY,
    wb_code CHAR(3) NOT NULL UNIQUE,
    iso2_code CHAR(2) NOT NULL,
    country_name TEXT NOT NULL,
    wb_region_code TEXT,
    wb_region TEXT,
    income_level_code TEXT,
    income_level TEXT,
    lending_type_code TEXT,
    lending_type TEXT
);
INSERT INTO wdi_countries (serial_no, wb_code, iso2_code, country_name, wb_region_code, wb_region, income_level_code, income_level, lending_type_code, lending_type) VALUES
    (1, 'ABW', 'AW', 'Aruba', 'LCN', 'Latin America & Caribbean', 'HIC', 'High income', 'LNX', 'Not classified'),
    (2, 'AFG', 'AF', 'Afghanistan', 'MEA', 'Middle East, North Africa, Afghanistan & Pakistan', 'LIC', 'Low income', 'IDX', 'IDA'),
    (3, 'AGO', 'AO', 'Angola', 'SSF', 'Sub-Saharan Africa', 'LMC', 'Lower middle income', 'IBD', 'IBRD'),
    (4, 'ALB', 'AL', 'Albania', 'ECS', 'Europe & Central Asia', 'UMC', 'Upper middle income', 'IBD', 'IBRD'),
    (5, 'AND', 'AD', 'Andorra', 'ECS', 'Europe & Central Asia', 'HIC', 'High income', 'LNX', 'Not classified'),
    (6, 'ARE', 'AE', 'United Arab Emirates', 'MEA', 'Middle East, North Africa, Afghanistan & Pakistan', 'HIC', 'High income', 'LNX', 'Not classified'),
    (7, 'ARG', 'AR', 'Argentina', 'LCN', 'Latin America & Caribbean', 'UMC', 'Upper middle income', 'IBD', 'IBRD'),
    (8, 'ARM', 'AM', 'Armenia', 'ECS', 'Europe & Central Asia', 'UMC', 'Upper middle income', 'IBD', 'IBRD'),
    (9, 'ASM', 'AS', 'American Samoa', 'EAS', 'East Asia & Pacific', 'HIC', 'High income', 'LNX', 'Not classified'),
    (10, 'ATG', 'AG', 'Antigua and Barbuda', 'LCN', 'Latin America & Caribbean', 'HIC', 'High income', 'IBD', 'IBRD'),
    (11, 'AUS', 'AU', 'Australia', 'EAS', 'East Asia & Pacific', 'HIC', 'High income', 'LNX', 'Not classified'),
    (12, 'AUT', 'AT', 'Austria', 'ECS', 'Europe & Central Asia', 'HIC', 'High income', 'LNX', 'Not classified'),
    (13, 'AZE', 'AZ', 'Azerbaijan', 'ECS', 'Europe & Central Asia', 'UMC', 'Upper middle income', 'IBD', 'IBRD'),
    (14, 'BDI', 'BI', 'Burundi', 'SSF', 'Sub-Saharan Africa', 'LIC', 'Low income', 'IDX', 'IDA'),
    (15, 'BEL', 'BE', 'Belgium', 'ECS', 'Europe & Central Asia', 'HIC', 'High income', 'LNX', 'Not classified'),
    (16, 'BEN', 'BJ', 'Benin', 'SSF', 'Sub-Saharan Africa', 'LMC', 'Lower middle income', 'IDX', 'IDA'),
    (17, 'BFA', 'BF', 'Burkina Faso', 'SSF', 'Sub-Saharan Africa', 'LIC', 'Low income', 'IDX', 'IDA'),
    (18, 'BGD', 'BD', 'Bangladesh', 'SAS', 'South Asia', 'LMC', 'Lower middle income', 'IDX', 'IDA'),
    (19, 'BGR', 'BG', 'Bulgaria', 'ECS', 'Europe & Central Asia', 'HIC', 'High income', 'IBD', 'IBRD'),
    (20, 'BHR', 'BH', 'Bahrain', 'MEA', 'Middle East, North Africa, Afghanistan & Pakistan', 'HIC', 'High income', 'LNX', 'Not classified'),
    (21, 'BHS', 'BS', 'Bahamas, The', 'LCN', 'Latin America & Caribbean', 'HIC', 'High income', 'LNX', 'Not classified'),
    (22, 'BIH', 'BA', 'Bosnia and Herzegovina', 'ECS', 'Europe & Central Asia', 'UMC', 'Upper middle income', 'IBD', 'IBRD'),
    (23, 'BLR', 'BY', 'Belarus', 'ECS', 'Europe & Central Asia', 'UMC', 'Upper middle income', 'IBD', 'IBRD'),
    (24, 'BLZ', 'BZ', 'Belize', 'LCN', 'Latin America & Caribbean', 'UMC', 'Upper middle income', 'IDB', 'Blend'),
    (25, 'BMU', 'BM', 'Bermuda', 'NAC', 'North America', 'HIC', 'High income', 'LNX', 'Not classified'),
    (26, 'BOL', 'BO', 'Bolivia', 'LCN', 'Latin America & Caribbean', 'LMC', 'Lower middle income', 'IBD', 'IBRD'),
    (27, 'BRA', 'BR', 'Brazil', 'LCN', 'Latin America & Caribbean', 'UMC', 'Upper middle income', 'IBD', 'IBRD'),
    (28, 'BRB', 'BB', 'Barbados', 'LCN', 'Latin America & Caribbean', 'HIC', 'High income', 'IBD', 'IBRD'),
    (29, 'BRN', 'BN', 'Brunei Darussalam', 'EAS', 'East Asia & Pacific', 'HIC', 'High income', 'LNX', 'Not classified'),
    (30, 'BTN', 'BT', 'Bhutan', 'SAS', 'South Asia', 'LMC', 'Lower middle income', 'IDX', 'IDA'),
    (31, 'BWA', 'BW', 'Botswana', 'SSF', 'Sub-Saharan Africa', 'UMC', 'Upper middle income', 'IBD', 'IBRD'),
    (32, 'CAF', 'CF', 'Central African Republic', 'SSF', 'Sub-Saharan Africa', 'LIC', 'Low income', 'IDX', 'IDA'),
    (33, 'CAN', 'CA', 'Canada', 'NAC', 'North America', 'HIC', 'High income', 'LNX', 'Not classified'),
    (34, 'CHE', 'CH', 'Switzerland', 'ECS', 'Europe & Central Asia', 'HIC', 'High income', 'LNX', 'Not classified'),
    (35, 'CHI', 'JG', 'Channel Islands', 'ECS', 'Europe & Central Asia', 'HIC', 'High income', 'LNX', 'Not classified'),
    (36, 'CHL', 'CL', 'Chile', 'LCN', 'Latin America & Caribbean', 'HIC', 'High income', 'IBD', 'IBRD'),
    (37, 'CHN', 'CN', 'China', 'EAS', 'East Asia & Pacific', 'UMC', 'Upper middle income', 'IBD', 'IBRD'),
    (38, 'CIV', 'CI', 'Cote d''Ivoire', 'SSF', 'Sub-Saharan Africa', 'LMC', 'Lower middle income', 'IDB', 'Blend'),
    (39, 'CMR', 'CM', 'Cameroon', 'SSF', 'Sub-Saharan Africa', 'LMC', 'Lower middle income', 'IDB', 'Blend'),
    (40, 'COD', 'CD', 'Congo, Dem. Rep.', 'SSF', 'Sub-Saharan Africa', 'LIC', 'Low income', 'IDX', 'IDA'),
    (41, 'COG', 'CG', 'Congo, Rep.', 'SSF', 'Sub-Saharan Africa', 'LMC', 'Lower middle income', 'IDB', 'Blend'),
    (42, 'COL', 'CO', 'Colombia', 'LCN', 'Latin America & Caribbean', 'UMC', 'Upper middle income', 'IBD', 'IBRD'),
    (43, 'COM', 'KM', 'Comoros', 'SSF', 'Sub-Saharan Africa', 'LMC', 'Lower middle income', 'IDX', 'IDA'),
    (44, 'CPV', 'CV', 'Cabo Verde', 'SSF', 'Sub-Saharan Africa', 'UMC', 'Upper middle income', 'IDB', 'Blend'),
    (45, 'CRI', 'CR', 'Costa Rica', 'LCN', 'Latin America & Caribbean', 'HIC', 'High income', 'IBD', 'IBRD'),
    (46, 'CUB', 'CU', 'Cuba', 'LCN', 'Latin America & Caribbean', 'UMC', 'Upper middle income', 'LNX', 'Not classified'),
    (47, 'CUW', 'CW', 'Curacao', 'LCN', 'Latin America & Caribbean', 'HIC', 'High income', 'LNX', 'Not classified'),
    (48, 'CYM', 'KY', 'Cayman Islands', 'LCN', 'Latin America & Caribbean', 'HIC', 'High income', 'LNX', 'Not classified'),
    (49, 'CYP', 'CY', 'Cyprus', 'ECS', 'Europe & Central Asia', 'HIC', 'High income', 'LNX', 'Not classified'),
    (50, 'CZE', 'CZ', 'Czechia', 'ECS', 'Europe & Central Asia', 'HIC', 'High income', 'LNX', 'Not classified'),
    (51, 'DEU', 'DE', 'Germany', 'ECS', 'Europe & Central Asia', 'HIC', 'High income', 'LNX', 'Not classified'),
    (52, 'DJI', 'DJ', 'Djibouti', 'MEA', 'Middle East, North Africa, Afghanistan & Pakistan', 'LMC', 'Lower middle income', 'IDX', 'IDA'),
    (53, 'DMA', 'DM', 'Dominica', 'LCN', 'Latin America & Caribbean', 'UMC', 'Upper middle income', 'IDB', 'Blend'),
    (54, 'DNK', 'DK', 'Denmark', 'ECS', 'Europe & Central Asia', 'HIC', 'High income', 'LNX', 'Not classified'),
    (55, 'DOM', 'DO', 'Dominican Republic', 'LCN', 'Latin America & Caribbean', 'UMC', 'Upper middle income', 'IBD', 'IBRD'),
    (56, 'DZA', 'DZ', 'Algeria', 'MEA', 'Middle East, North Africa, Afghanistan & Pakistan', 'UMC', 'Upper middle income', 'IBD', 'IBRD'),
    (57, 'ECU', 'EC', 'Ecuador', 'LCN', 'Latin America & Caribbean', 'UMC', 'Upper middle income', 'IBD', 'IBRD'),
    (58, 'EGY', 'EG', 'Egypt, Arab Rep.', 'MEA', 'Middle East, North Africa, Afghanistan & Pakistan', 'LMC', 'Lower middle income', 'IBD', 'IBRD'),
    (59, 'ERI', 'ER', 'Eritrea', 'SSF', 'Sub-Saharan Africa', 'LIC', 'Low income', 'IDX', 'IDA'),
    (60, 'ESP', 'ES', 'Spain', 'ECS', 'Europe & Central Asia', 'HIC', 'High income', 'LNX', 'Not classified'),
    (61, 'EST', 'EE', 'Estonia', 'ECS', 'Europe & Central Asia', 'HIC', 'High income', 'LNX', 'Not classified'),
    (62, 'ETH', 'ET', 'Ethiopia', 'SSF', 'Sub-Saharan Africa', 'LIC', 'Low income', 'IDX', 'IDA'),
    (63, 'FIN', 'FI', 'Finland', 'ECS', 'Europe & Central Asia', 'HIC', 'High income', 'LNX', 'Not classified'),
    (64, 'FJI', 'FJ', 'Fiji', 'EAS', 'East Asia & Pacific', 'UMC', 'Upper middle income', 'IDB', 'Blend'),
    (65, 'FRA', 'FR', 'France', 'ECS', 'Europe & Central Asia', 'HIC', 'High income', 'LNX', 'Not classified'),
    (66, 'FRO', 'FO', 'Faroe Islands', 'ECS', 'Europe & Central Asia', 'HIC', 'High income', 'LNX', 'Not classified'),
    (67, 'FSM', 'FM', 'Micronesia, Fed. Sts.', 'EAS', 'East Asia & Pacific', 'UMC', 'Upper middle income', 'IDX', 'IDA'),
    (68, 'GAB', 'GA', 'Gabon', 'SSF', 'Sub-Saharan Africa', 'UMC', 'Upper middle income', 'IBD', 'IBRD'),
    (69, 'GBR', 'GB', 'United Kingdom', 'ECS', 'Europe & Central Asia', 'HIC', 'High income', 'LNX', 'Not classified'),
    (70, 'GEO', 'GE', 'Georgia', 'ECS', 'Europe & Central Asia', 'UMC', 'Upper middle income', 'IBD', 'IBRD'),
    (71, 'GHA', 'GH', 'Ghana', 'SSF', 'Sub-Saharan Africa', 'LMC', 'Lower middle income', 'IDX', 'IDA'),
    (72, 'GIB', 'GI', 'Gibraltar', 'ECS', 'Europe & Central Asia', 'HIC', 'High income', 'LNX', 'Not classified'),
    (73, 'GIN', 'GN', 'Guinea', 'SSF', 'Sub-Saharan Africa', 'LMC', 'Lower middle income', 'IDX', 'IDA'),
    (74, 'GMB', 'GM', 'Gambia, The', 'SSF', 'Sub-Saharan Africa', 'LIC', 'Low income', 'IDX', 'IDA'),
    (75, 'GNB', 'GW', 'Guinea-Bissau', 'SSF', 'Sub-Saharan Africa', 'LIC', 'Low income', 'IDX', 'IDA'),
    (76, 'GNQ', 'GQ', 'Equatorial Guinea', 'SSF', 'Sub-Saharan Africa', 'UMC', 'Upper middle income', 'IBD', 'IBRD'),
    (77, 'GRC', 'GR', 'Greece', 'ECS', 'Europe & Central Asia', 'HIC', 'High income', 'LNX', 'Not classified'),
    (78, 'GRD', 'GD', 'Grenada', 'LCN', 'Latin America & Caribbean', 'UMC', 'Upper middle income', 'IDB', 'Blend'),
    (79, 'GRL', 'GL', 'Greenland', 'ECS', 'Europe & Central Asia', 'HIC', 'High income', 'LNX', 'Not classified'),
    (80, 'GTM', 'GT', 'Guatemala', 'LCN', 'Latin America & Caribbean', 'UMC', 'Upper middle income', 'IBD', 'IBRD'),
    (81, 'GUM', 'GU', 'Guam', 'EAS', 'East Asia & Pacific', 'HIC', 'High income', 'LNX', 'Not classified'),
    (82, 'GUY', 'GY', 'Guyana', 'LCN', 'Latin America & Caribbean', 'HIC', 'High income', 'IDX', 'IDA'),
    (83, 'HKG', 'HK', 'Hong Kong SAR, China', 'EAS', 'East Asia & Pacific', 'HIC', 'High income', 'LNX', 'Not classified'),
    (84, 'HND', 'HN', 'Honduras', 'LCN', 'Latin America & Caribbean', 'LMC', 'Lower middle income', 'IDX', 'IDA'),
    (85, 'HRV', 'HR', 'Croatia', 'ECS', 'Europe & Central Asia', 'HIC', 'High income', 'IBD', 'IBRD'),
    (86, 'HTI', 'HT', 'Haiti', 'LCN', 'Latin America & Caribbean', 'LMC', 'Lower middle income', 'IDX', 'IDA'),
    (87, 'HUN', 'HU', 'Hungary', 'ECS', 'Europe & Central Asia', 'HIC', 'High income', 'LNX', 'Not classified'),
    (88, 'IDN', 'ID', 'Indonesia', 'EAS', 'East Asia & Pacific', 'UMC', 'Upper middle income', 'IBD', 'IBRD'),
    (89, 'IMN', 'IM', 'Isle of Man', 'ECS', 'Europe & Central Asia', 'HIC', 'High income', 'LNX', 'Not classified'),
    (90, 'IND', 'IN', 'India', 'SAS', 'South Asia', 'LMC', 'Lower middle income', 'IBD', 'IBRD'),
    (91, 'IRL', 'IE', 'Ireland', 'ECS', 'Europe & Central Asia', 'HIC', 'High income', 'LNX', 'Not classified'),
    (92, 'IRN', 'IR', 'Iran, Islamic Rep.', 'MEA', 'Middle East, North Africa, Afghanistan & Pakistan', 'UMC', 'Upper middle income', 'IBD', 'IBRD'),
    (93, 'IRQ', 'IQ', 'Iraq', 'MEA', 'Middle East, North Africa, Afghanistan & Pakistan', 'UMC', 'Upper middle income', 'IBD', 'IBRD'),
    (94, 'ISL', 'IS', 'Iceland', 'ECS', 'Europe & Central Asia', 'HIC', 'High income', 'LNX', 'Not classified'),
    (95, 'ISR', 'IL', 'Israel', 'MEA', 'Middle East, North Africa, Afghanistan & Pakistan', 'HIC', 'High income', 'LNX', 'Not classified'),
    (96, 'ITA', 'IT', 'Italy', 'ECS', 'Europe & Central Asia', 'HIC', 'High income', 'LNX', 'Not classified'),
    (97, 'JAM', 'JM', 'Jamaica', 'LCN', 'Latin America & Caribbean', 'UMC', 'Upper middle income', 'IBD', 'IBRD'),
    (98, 'JOR', 'JO', 'Jordan', 'MEA', 'Middle East, North Africa, Afghanistan & Pakistan', 'UMC', 'Upper middle income', 'IBD', 'IBRD'),
    (99, 'JPN', 'JP', 'Japan', 'EAS', 'East Asia & Pacific', 'HIC', 'High income', 'LNX', 'Not classified'),
    (100, 'KAZ', 'KZ', 'Kazakhstan', 'ECS', 'Europe & Central Asia', 'UMC', 'Upper middle income', 'IBD', 'IBRD'),
    (101, 'KEN', 'KE', 'Kenya', 'SSF', 'Sub-Saharan Africa', 'LMC', 'Lower middle income', 'IDB', 'Blend'),
    (102, 'KGZ', 'KG', 'Kyrgyz Republic', 'ECS', 'Europe & Central Asia', 'LMC', 'Lower middle income', 'IDX', 'IDA'),
    (103, 'KHM', 'KH', 'Cambodia', 'EAS', 'East Asia & Pacific', 'LMC', 'Lower middle income', 'IDX', 'IDA'),
    (104, 'KIR', 'KI', 'Kiribati', 'EAS', 'East Asia & Pacific', 'LMC', 'Lower middle income', 'IDX', 'IDA'),
    (105, 'KNA', 'KN', 'St. Kitts and Nevis', 'LCN', 'Latin America & Caribbean', 'HIC', 'High income', 'IBD', 'IBRD'),
    (106, 'KOR', 'KR', 'Korea, Rep.', 'EAS', 'East Asia & Pacific', 'HIC', 'High income', 'LNX', 'Not classified'),
    (107, 'KWT', 'KW', 'Kuwait', 'MEA', 'Middle East, North Africa, Afghanistan & Pakistan', 'HIC', 'High income', 'LNX', 'Not classified'),
    (108, 'LAO', 'LA', 'Lao PDR', 'EAS', 'East Asia & Pacific', 'LMC', 'Lower middle income', 'IDX', 'IDA'),
    (109, 'LBN', 'LB', 'Lebanon', 'MEA', 'Middle East, North Africa, Afghanistan & Pakistan', 'LMC', 'Lower middle income', 'IBD', 'IBRD'),
    (110, 'LBR', 'LR', 'Liberia', 'SSF', 'Sub-Saharan Africa', 'LIC', 'Low income', 'IDX', 'IDA'),
    (111, 'LBY', 'LY', 'Libya', 'MEA', 'Middle East, North Africa, Afghanistan & Pakistan', 'UMC', 'Upper middle income', 'IBD', 'IBRD'),
    (112, 'LCA', 'LC', 'St. Lucia', 'LCN', 'Latin America & Caribbean', 'UMC', 'Upper middle income', 'IDB', 'Blend'),
    (113, 'LIE', 'LI', 'Liechtenstein', 'ECS', 'Europe & Central Asia', 'HIC', 'High income', 'LNX', 'Not classified'),
    (114, 'LKA', 'LK', 'Sri Lanka', 'SAS', 'South Asia', 'UMC', 'Upper middle income', 'IDX', 'IDA'),
    (115, 'LSO', 'LS', 'Lesotho', 'SSF', 'Sub-Saharan Africa', 'LMC', 'Lower middle income', 'IDX', 'IDA'),
    (116, 'LTU', 'LT', 'Lithuania', 'ECS', 'Europe & Central Asia', 'HIC', 'High income', 'LNX', 'Not classified'),
    (117, 'LUX', 'LU', 'Luxembourg', 'ECS', 'Europe & Central Asia', 'HIC', 'High income', 'LNX', 'Not classified'),
    (118, 'LVA', 'LV', 'Latvia', 'ECS', 'Europe & Central Asia', 'HIC', 'High income', 'LNX', 'Not classified'),
    (119, 'MAC', 'MO', 'Macao SAR, China', 'EAS', 'East Asia & Pacific', 'HIC', 'High income', 'LNX', 'Not classified'),
    (120, 'MAF', 'MF', 'St. Martin (French part)', 'LCN', 'Latin America & Caribbean', 'HIC', 'High income', 'LNX', 'Not classified'),
    (121, 'MAR', 'MA', 'Morocco', 'MEA', 'Middle East, North Africa, Afghanistan & Pakistan', 'LMC', 'Lower middle income', 'IBD', 'IBRD'),
    (122, 'MCO', 'MC', 'Monaco', 'ECS', 'Europe & Central Asia', 'HIC', 'High income', 'LNX', 'Not classified'),
    (123, 'MDA', 'MD', 'Moldova', 'ECS', 'Europe & Central Asia', 'UMC', 'Upper middle income', 'IBD', 'IBRD'),
    (124, 'MDG', 'MG', 'Madagascar', 'SSF', 'Sub-Saharan Africa', 'LIC', 'Low income', 'IDX', 'IDA'),
    (125, 'MDV', 'MV', 'Maldives', 'SAS', 'South Asia', 'UMC', 'Upper middle income', 'IDX', 'IDA'),
    (126, 'MEX', 'MX', 'Mexico', 'LCN', 'Latin America & Caribbean', 'UMC', 'Upper middle income', 'IBD', 'IBRD'),
    (127, 'MHL', 'MH', 'Marshall Islands', 'EAS', 'East Asia & Pacific', 'UMC', 'Upper middle income', 'IDX', 'IDA'),
    (128, 'MKD', 'MK', 'North Macedonia', 'ECS', 'Europe & Central Asia', 'UMC', 'Upper middle income', 'IBD', 'IBRD'),
    (129, 'MLI', 'ML', 'Mali', 'SSF', 'Sub-Saharan Africa', 'LIC', 'Low income', 'IDX', 'IDA'),
    (130, 'MLT', 'MT', 'Malta', 'MEA', 'Middle East, North Africa, Afghanistan & Pakistan', 'HIC', 'High income', 'LNX', 'Not classified'),
    (131, 'MMR', 'MM', 'Myanmar', 'EAS', 'East Asia & Pacific', 'LMC', 'Lower middle income', 'IDX', 'IDA'),
    (132, 'MNE', 'ME', 'Montenegro', 'ECS', 'Europe & Central Asia', 'UMC', 'Upper middle income', 'IBD', 'IBRD'),
    (133, 'MNG', 'MN', 'Mongolia', 'EAS', 'East Asia & Pacific', 'UMC', 'Upper middle income', 'IBD', 'IBRD'),
    (134, 'MNP', 'MP', 'Northern Mariana Islands', 'EAS', 'East Asia & Pacific', 'HIC', 'High income', 'LNX', 'Not classified'),
    (135, 'MOZ', 'MZ', 'Mozambique', 'SSF', 'Sub-Saharan Africa', 'LIC', 'Low income', 'IDX', 'IDA'),
    (136, 'MRT', 'MR', 'Mauritania', 'SSF', 'Sub-Saharan Africa', 'LMC', 'Lower middle income', 'IDX', 'IDA'),
    (137, 'MUS', 'MU', 'Mauritius', 'SSF', 'Sub-Saharan Africa', 'UMC', 'Upper middle income', 'IBD', 'IBRD'),
    (138, 'MWI', 'MW', 'Malawi', 'SSF', 'Sub-Saharan Africa', 'LIC', 'Low income', 'IDX', 'IDA'),
    (139, 'MYS', 'MY', 'Malaysia', 'EAS', 'East Asia & Pacific', 'UMC', 'Upper middle income', 'IBD', 'IBRD'),
    (140, 'NAM', 'NA', 'Namibia', 'SSF', 'Sub-Saharan Africa', 'LMC', 'Lower middle income', 'IBD', 'IBRD'),
    (141, 'NCL', 'NC', 'New Caledonia', 'EAS', 'East Asia & Pacific', 'HIC', 'High income', 'LNX', 'Not classified'),
    (142, 'NER', 'NE', 'Niger', 'SSF', 'Sub-Saharan Africa', 'LIC', 'Low income', 'IDX', 'IDA'),
    (143, 'NGA', 'NG', 'Nigeria', 'SSF', 'Sub-Saharan Africa', 'LMC', 'Lower middle income', 'IDB', 'Blend'),
    (144, 'NIC', 'NI', 'Nicaragua', 'LCN', 'Latin America & Caribbean', 'LMC', 'Lower middle income', 'IDX', 'IDA'),
    (145, 'NLD', 'NL', 'Netherlands', 'ECS', 'Europe & Central Asia', 'HIC', 'High income', 'LNX', 'Not classified'),
    (146, 'NOR', 'NO', 'Norway', 'ECS', 'Europe & Central Asia', 'HIC', 'High income', 'LNX', 'Not classified'),
    (147, 'NPL', 'NP', 'Nepal', 'SAS', 'South Asia', 'LMC', 'Lower middle income', 'IDX', 'IDA'),
    (148, 'NRU', 'NR', 'Naoero', 'EAS', 'East Asia & Pacific', 'HIC', 'High income', 'IBD', 'IBRD'),
    (149, 'NZL', 'NZ', 'New Zealand', 'EAS', 'East Asia & Pacific', 'HIC', 'High income', 'LNX', 'Not classified'),
    (150, 'OMN', 'OM', 'Oman', 'MEA', 'Middle East, North Africa, Afghanistan & Pakistan', 'HIC', 'High income', 'LNX', 'Not classified'),
    (151, 'PAK', 'PK', 'Pakistan', 'MEA', 'Middle East, North Africa, Afghanistan & Pakistan', 'LMC', 'Lower middle income', 'IDB', 'Blend'),
    (152, 'PAN', 'PA', 'Panama', 'LCN', 'Latin America & Caribbean', 'HIC', 'High income', 'IBD', 'IBRD'),
    (153, 'PER', 'PE', 'Peru', 'LCN', 'Latin America & Caribbean', 'UMC', 'Upper middle income', 'IBD', 'IBRD'),
    (154, 'PHL', 'PH', 'Philippines', 'EAS', 'East Asia & Pacific', 'UMC', 'Upper middle income', 'IBD', 'IBRD'),
    (155, 'PLW', 'PW', 'Palau', 'EAS', 'East Asia & Pacific', 'HIC', 'High income', 'IBD', 'IBRD'),
    (156, 'PNG', 'PG', 'Papua New Guinea', 'EAS', 'East Asia & Pacific', 'LMC', 'Lower middle income', 'IDB', 'Blend'),
    (157, 'POL', 'PL', 'Poland', 'ECS', 'Europe & Central Asia', 'HIC', 'High income', 'IBD', 'IBRD'),
    (158, 'PRI', 'PR', 'Puerto Rico (US)', 'LCN', 'Latin America & Caribbean', 'HIC', 'High income', 'LNX', 'Not classified'),
    (159, 'PRK', 'KP', 'Korea, Dem. People''s Rep.', 'EAS', 'East Asia & Pacific', 'LIC', 'Low income', 'LNX', 'Not classified'),
    (160, 'PRT', 'PT', 'Portugal', 'ECS', 'Europe & Central Asia', 'HIC', 'High income', 'LNX', 'Not classified'),
    (161, 'PRY', 'PY', 'Paraguay', 'LCN', 'Latin America & Caribbean', 'UMC', 'Upper middle income', 'IBD', 'IBRD'),
    (162, 'PSE', 'PS', 'West Bank and Gaza', 'MEA', 'Middle East, North Africa, Afghanistan & Pakistan', 'LMC', 'Lower middle income', 'LNX', 'Not classified'),
    (163, 'PYF', 'PF', 'French Polynesia', 'EAS', 'East Asia & Pacific', 'HIC', 'High income', 'LNX', 'Not classified'),
    (164, 'QAT', 'QA', 'Qatar', 'MEA', 'Middle East, North Africa, Afghanistan & Pakistan', 'HIC', 'High income', 'LNX', 'Not classified'),
    (165, 'ROU', 'RO', 'Romania', 'ECS', 'Europe & Central Asia', 'HIC', 'High income', 'IBD', 'IBRD'),
    (166, 'RUS', 'RU', 'Russian Federation', 'ECS', 'Europe & Central Asia', 'HIC', 'High income', 'IBD', 'IBRD'),
    (167, 'RWA', 'RW', 'Rwanda', 'SSF', 'Sub-Saharan Africa', 'LIC', 'Low income', 'IDX', 'IDA'),
    (168, 'SAU', 'SA', 'Saudi Arabia', 'MEA', 'Middle East, North Africa, Afghanistan & Pakistan', 'HIC', 'High income', 'LNX', 'Not classified'),
    (169, 'SDN', 'SD', 'Sudan', 'SSF', 'Sub-Saharan Africa', 'LIC', 'Low income', 'IDX', 'IDA'),
    (170, 'SEN', 'SN', 'Senegal', 'SSF', 'Sub-Saharan Africa', 'LMC', 'Lower middle income', 'IDX', 'IDA'),
    (171, 'SGP', 'SG', 'Singapore', 'EAS', 'East Asia & Pacific', 'HIC', 'High income', 'LNX', 'Not classified'),
    (172, 'SLB', 'SB', 'Solomon Islands', 'EAS', 'East Asia & Pacific', 'LMC', 'Lower middle income', 'IDX', 'IDA'),
    (173, 'SLE', 'SL', 'Sierra Leone', 'SSF', 'Sub-Saharan Africa', 'LIC', 'Low income', 'IDX', 'IDA'),
    (174, 'SLV', 'SV', 'El Salvador', 'LCN', 'Latin America & Caribbean', 'UMC', 'Upper middle income', 'IBD', 'IBRD'),
    (175, 'SMR', 'SM', 'San Marino', 'ECS', 'Europe & Central Asia', 'HIC', 'High income', 'LNX', 'Not classified'),
    (176, 'SOM', 'SO', 'Somalia, Fed. Rep.', 'SSF', 'Sub-Saharan Africa', 'LIC', 'Low income', 'IDX', 'IDA'),
    (177, 'SRB', 'RS', 'Serbia', 'ECS', 'Europe & Central Asia', 'UMC', 'Upper middle income', 'IBD', 'IBRD'),
    (178, 'SSD', 'SS', 'South Sudan', 'SSF', 'Sub-Saharan Africa', 'LIC', 'Low income', 'IDX', 'IDA'),
    (179, 'STP', 'ST', 'Sao Tome and Principe', 'SSF', 'Sub-Saharan Africa', 'LMC', 'Lower middle income', 'IDX', 'IDA'),
    (180, 'SUR', 'SR', 'Suriname', 'LCN', 'Latin America & Caribbean', 'UMC', 'Upper middle income', 'IDB', 'Blend'),
    (181, 'SVK', 'SK', 'Slovak Republic', 'ECS', 'Europe & Central Asia', 'HIC', 'High income', 'LNX', 'Not classified'),
    (182, 'SVN', 'SI', 'Slovenia', 'ECS', 'Europe & Central Asia', 'HIC', 'High income', 'LNX', 'Not classified'),
    (183, 'SWE', 'SE', 'Sweden', 'ECS', 'Europe & Central Asia', 'HIC', 'High income', 'LNX', 'Not classified'),
    (184, 'SWZ', 'SZ', 'Eswatini', 'SSF', 'Sub-Saharan Africa', 'LMC', 'Lower middle income', 'IDB', 'Blend'),
    (185, 'SXM', 'SX', 'Sint Maarten (Dutch part)', 'LCN', 'Latin America & Caribbean', 'HIC', 'High income', 'LNX', 'Not classified'),
    (186, 'SYC', 'SC', 'Seychelles', 'SSF', 'Sub-Saharan Africa', 'HIC', 'High income', 'IBD', 'IBRD'),
    (187, 'SYR', 'SY', 'Syrian Arab Republic', 'MEA', 'Middle East, North Africa, Afghanistan & Pakistan', 'LIC', 'Low income', 'IDX', 'IDA'),
    (188, 'TCA', 'TC', 'Turks and Caicos Islands', 'LCN', 'Latin America & Caribbean', 'HIC', 'High income', 'LNX', 'Not classified'),
    (189, 'TCD', 'TD', 'Chad', 'SSF', 'Sub-Saharan Africa', 'LIC', 'Low income', 'IDX', 'IDA'),
    (190, 'TGO', 'TG', 'Togo', 'SSF', 'Sub-Saharan Africa', 'LMC', 'Lower middle income', 'IDX', 'IDA'),
    (191, 'THA', 'TH', 'Thailand', 'EAS', 'East Asia & Pacific', 'UMC', 'Upper middle income', 'IBD', 'IBRD'),
    (192, 'TJK', 'TJ', 'Tajikistan', 'ECS', 'Europe & Central Asia', 'LMC', 'Lower middle income', 'IDX', 'IDA'),
    (193, 'TKM', 'TM', 'Turkmenistan', 'ECS', 'Europe & Central Asia', 'UMC', 'Upper middle income', 'IBD', 'IBRD'),
    (194, 'TLS', 'TL', 'Timor-Leste', 'EAS', 'East Asia & Pacific', 'LMC', 'Lower middle income', 'IDB', 'Blend'),
    (195, 'TON', 'TO', 'Tonga', 'EAS', 'East Asia & Pacific', 'UMC', 'Upper middle income', 'IDX', 'IDA'),
    (196, 'TTO', 'TT', 'Trinidad and Tobago', 'LCN', 'Latin America & Caribbean', 'HIC', 'High income', 'IBD', 'IBRD'),
    (197, 'TUN', 'TN', 'Tunisia', 'MEA', 'Middle East, North Africa, Afghanistan & Pakistan', 'LMC', 'Lower middle income', 'IBD', 'IBRD'),
    (198, 'TUR', 'TR', 'Turkiye', 'ECS', 'Europe & Central Asia', 'UMC', 'Upper middle income', 'IBD', 'IBRD'),
    (199, 'TUV', 'TV', 'Tuvalu', 'EAS', 'East Asia & Pacific', 'UMC', 'Upper middle income', 'IDX', 'IDA'),
    (200, 'TZA', 'TZ', 'Tanzania', 'SSF', 'Sub-Saharan Africa', 'LMC', 'Lower middle income', 'IDX', 'IDA'),
    (201, 'UGA', 'UG', 'Uganda', 'SSF', 'Sub-Saharan Africa', 'LIC', 'Low income', 'IDX', 'IDA'),
    (202, 'UKR', 'UA', 'Ukraine', 'ECS', 'Europe & Central Asia', 'UMC', 'Upper middle income', 'IBD', 'IBRD'),
    (203, 'URY', 'UY', 'Uruguay', 'LCN', 'Latin America & Caribbean', 'HIC', 'High income', 'IBD', 'IBRD'),
    (204, 'USA', 'US', 'United States', 'NAC', 'North America', 'HIC', 'High income', 'LNX', 'Not classified'),
    (205, 'UZB', 'UZ', 'Uzbekistan', 'ECS', 'Europe & Central Asia', 'LMC', 'Lower middle income', 'IDB', 'Blend'),
    (206, 'VCT', 'VC', 'St. Vincent and the Grenadines', 'LCN', 'Latin America & Caribbean', 'UMC', 'Upper middle income', 'IDB', 'Blend'),
    (207, 'VEN', 'VE', 'Venezuela, RB', 'LCN', 'Latin America & Caribbean', 'LMC', 'Lower middle income', 'IBD', 'IBRD'),
    (208, 'VGB', 'VG', 'British Virgin Islands', 'LCN', 'Latin America & Caribbean', 'HIC', 'High income', 'LNX', 'Not classified'),
    (209, 'VIR', 'VI', 'Virgin Islands (U.S.)', 'LCN', 'Latin America & Caribbean', 'HIC', 'High income', 'LNX', 'Not classified'),
    (210, 'VNM', 'VN', 'Viet Nam', 'EAS', 'East Asia & Pacific', 'UMC', 'Upper middle income', 'IBD', 'IBRD'),
    (211, 'VUT', 'VU', 'Vanuatu', 'EAS', 'East Asia & Pacific', 'LMC', 'Lower middle income', 'IDX', 'IDA'),
    (212, 'WSM', 'WS', 'Samoa', 'EAS', 'East Asia & Pacific', 'UMC', 'Upper middle income', 'IDX', 'IDA'),
    (213, 'XKX', 'XK', 'Kosovo', 'ECS', 'Europe & Central Asia', 'UMC', 'Upper middle income', 'IDX', 'IDA'),
    (214, 'YEM', 'YE', 'Yemen, Rep.', 'MEA', 'Middle East, North Africa, Afghanistan & Pakistan', 'LIC', 'Low income', 'IDX', 'IDA'),
    (215, 'ZAF', 'ZA', 'South Africa', 'SSF', 'Sub-Saharan Africa', 'UMC', 'Upper middle income', 'IBD', 'IBRD'),
    (216, 'ZMB', 'ZM', 'Zambia', 'SSF', 'Sub-Saharan Africa', 'LMC', 'Lower middle income', 'IDX', 'IDA'),
    (217, 'ZWE', 'ZW', 'Zimbabwe', 'SSF', 'Sub-Saharan Africa', 'LMC', 'Lower middle income', 'IDB', 'Blend');
COMMIT;
